import { defaults, validate, fitBoxLayoutFromBottom } from './geometry.mjs';

// Full configurations keep every selection independent of the previous model.
export const presets = [
  {
    id: 'river',
    label: 'Green river haunch',
    description: 'Three flowing green plate-girder spans, a riverside sidewalk and open steel railings.',
    config: {
      ...defaults,
      material: 'steel',
      steelColor: 'green',
      lighting: 'poles',
      width: 13.2,
      girders: 5,
      overhang: 1.3,
      depth: 1.2,
      continuous: true,
      variableDepth: true,
      pierDepth: 2.1,
      taper: 35,
      barrierType: 'steel',
      leftRailing: '210A',
      rightRailing: '210A',
      sidewalkSide: 'right',
      sidewalkWidth: 2,
      abutmentType: 'return',
      wingAngle: 35,
      elevation: 6.8,
      rise: 0.45,
      approach: 24,
      pierType: 'bent',
      columns: 2,
      columnDiameter: 1.1,
      bentWidth: 1.8,
      bentThickness: 0.9,
      bentEndThickness: 0.9,
      environment: 'rural',
      seed: 24,
      laneWidth: 3.5,
      movingTraffic: true,
      spans: [20, 28, 20].map(length => ({ length, obstacle: 'water', width: 18, elevation: 0, angle: 90 })),
    },
  },
  {
    id: 'nebt',
    label: 'NEBT river crossing',
    description: 'A compact two-span precast bridge with broad shoulders and simple rural approaches.',
    config: {
      ...defaults,
      material: 'concrete',
      width: 11.4,
      girders: 4,
      overhang: 1.2,
      depth: 1.4,
      elevation: 6.1,
      rise: 0.3,
      approach: 22,
      barrierType: 'steel',
      leftRailing: '210A',
      rightRailing: '210A',
      abutmentType: 'return',
      wingAngle: 45,
      pierType: 'bent',
      columns: 2,
      columnDiameter: 1.1,
      bentWidth: 1.9,
      bentThickness: 1,
      environment: 'rural',
      seed: 7,
      laneWidth: 3.5,
      movingTraffic: true,
      spans: [26, 26].map(length => ({ length, obstacle: 'water', width: 22, elevation: 0, angle: 85 })),
    },
  },
  {
    id: 'box',
    label: 'Curved twin boxes',
    description: 'Blue paired box girders sweep across city roads and a central railway.',
    config: {
      ...defaults,
      material: 'box',
      steelColor: 'blue',
      girders: 2,
      boxTopWidth: 5.1,
      boxBottomWidth: 3.55,
      overhang: 3.75,
      width: 13.6,
      depth: 1.3,
      continuous: true,
      variableDepth: true,
      pierDepth: 2.2,
      taper: 30,
      curved: true,
      radius: 160,
      direction: 1,
      skew: 10,
      elevation: 7.4,
      rise: 0.45,
      approach: 25,
      barrierType: 'steel',
      leftRailing: '210C',
      rightRailing: '210C',
      sidewalkSide: 'right',
      sidewalkWidth: 2.5,
      pierType: 'hammerhead',
      columns: 1,
      columnDiameter: 1.5,
      hammerheadWidth: 2.5,
      hammerheadThickness: 1,
      environment: 'urban',
      seed: 31,
      laneWidth: 3.5,
      movingTraffic: true,
      spans: [
        { length: 24, obstacle: 'road', width: 10, elevation: 0, angle: 80 },
        { length: 32, obstacle: 'rail', width: 7, elevation: 0, angle: 90 },
        { length: 24, obstacle: 'road', width: 10, elevation: 0, angle: 100 },
      ],
    },
  },
  {
    id: 'slab',
    label: 'Low park bridge',
    description: 'A shallow concrete slab with a gentle pier haunch, sidewalk and open views of the water.',
    config: {
      ...defaults,
      material: 'slab',
      width: 10.6,
      slabDepth: 0.5,
      continuous: true,
      variableDepth: true,
      pierDepth: 0.85,
      taper: 40,
      elevation: 3.6,
      rise: 0.18,
      approach: 18,
      barrierType: 'steel',
      leftRailing: '210A',
      rightRailing: '210A',
      sidewalkSide: 'right',
      sidewalkWidth: 1.8,
      abutmentType: 'return',
      wingAngle: 40,
      pierType: 'wall',
      wallThickness: 0.55,
      environment: 'rural',
      seed: 43,
      laneWidth: 3.5,
      movingTraffic: true,
      spans: [16, 16].map(length => ({ length, obstacle: 'water', width: 12, elevation: 0, angle: 90 })),
    },
  },
  {
    id: 'urban',
    label: 'Urban boulevard',
    description: 'Four lanes, a concrete median and sidewalks on both sides, carried by square-column bents.',
    config: {
      ...defaults,
      material: 'concrete',
      width: 23.6,
      girders: 7,
      overhang: 1.5,
      depth: 1.6,
      laneCount: 4,
      laneWidth: 3.5,
      medianType: 'barrier',
      sidewalkSide: 'both',
      sidewalkWidth: 2.5,
      barrierType: 'concrete',
      pierType: 'bent',
      columns: 3,
      columnShape: 'square',
      columnDiameter: 1.2,
      bentWidth: 2.2,
      bentThickness: 1.1,
      bentEndThickness: 1.1,
      skew: 8,
      elevation: 7.4,
      profile: 'constant',
      grade: 0.5,
      approach: 26,
      environment: 'urban',
      seed: 12,
      movingTraffic: true,
      spans: [
        { length: 26, obstacle: 'road', width: 14, elevation: 0, angle: 90 },
        { length: 30, obstacle: 'rail', width: 8, elevation: 0, angle: 90 },
        { length: 26, obstacle: 'road', width: 14, elevation: 0, angle: 90 },
      ],
    },
  },
  {
    id: 'weathered',
    label: 'Weathered railway overpass',
    description: 'A skewed single-span steel bridge with warm weathered girders and return walls.',
    config: {
      ...defaults,
      material: 'steel',
      steelColor: 'weathered',
      width: 11.4,
      girders: 4,
      overhang: 1.2,
      depth: 1.65,
      skew: 25,
      elevation: 7.3,
      rise: 0.25,
      approach: 23,
      barrierType: 'steel',
      leftRailing: '210A',
      rightRailing: '210A',
      abutmentType: 'return',
      wingAngle: 35,
      environment: 'rural',
      seed: 56,
      laneWidth: 3.5,
      movingTraffic: true,
      spans: [{ length: 36, obstacle: 'rail', width: 7, elevation: 0, angle: 65 }],
    },
  },
  {
    id: 'cycle',
    label: 'Pedestrian bridge',
    description: 'A 4.2 m single-box pedestrian and cycle bridge with moving cyclists, a mirror river and dynamic clouds.',
    config: {
      ...defaults,
      material: 'box',
      trafficMode: 'cyclists',
      approachBarrier: 'extend',
      lighting: 'handrail',
      lightSpacing: 3,
      lightColor: 'warm',
      skyMode: 'clouds',
      waterStyle: 'glossy',
      width: 4.2,
      girders: 1,
      overhang: 2.1,
      boxTopWidth: 3,
      boxBottomWidth: 1.7,
      depth: 1.1,
      variableDepth: true,
      pierDepth: 1.7,
      laneCount: 1,
      laneWidth: 1.8,
      leftRailing: '20C',
      rightRailing: '20C',
      barrierType: 'steel',
      elevation: 6.2,
      rise: 0.25,
      approach: 18,
      environment: 'rural',
      seed: 48,
      spans: [{ length: 28, obstacle: 'water', width: 15, elevation: 0, angle: 90 }],
    },
  },
  {
    id: 'psbox',
    label: 'Box girder viaduct',
    description: 'Twin prestressed concrete boxes under one 16.5 m deck, curved and haunched over tall wall piers, crossing a road, a river and a railway.',
    config: {
      ...defaults,
      material: 'psbox',
      structureSystem: 'girder',
      psboxCount: 2,
      width: 16.5,
      laneCount: 4,
      depth: 2.3,
      variableDepth: true,
      pierDepth: 4.2,
      taper: 32,
      continuous: true,
      curved: true,
      radius: 520,
      direction: -1,
      elevation: 16,
      profile: 'crest',
      rise: 1.1,
      approach: 30,
      leftRailing: '311A',
      rightRailing: '311A',
      lighting: 'poles',
      lightSides: 'right',
      pierType: 'wall',
      wallThickness: 1.8,
      sceneWidth: 190,
      environment: 'rural',
      seed: 61,
      spans: [
        { length: 44, obstacle: 'road', width: 12, elevation: 0, angle: 80 },
        { length: 68, obstacle: 'water', width: 42, elevation: 0, angle: 90 },
        { length: 44, obstacle: 'rail', width: 8, elevation: 0, angle: 95 },
      ],
    },
  },
  {
    id: 'strutted',
    label: 'Strutted frame · béquilles',
    description: 'A concrete box frame on two inclined legs founded on the banks, no bearings at the leg joints.',
    config: {
      ...defaults,
      structureSystem: 'strutted',
      strutAngle: 30,
      material: 'psbox',
      width: 12.4,
      depth: 1.5,
      variableDepth: true,
      pierDepth: 3.1,
      taper: 30,
      continuous: true,
      elevation: 14,
      rise: 0.9,
      approach: 28,
      leftRailing: '311',
      rightRailing: '311',
      environment: 'rural',
      terrainMode: 'fall',
      seed: 72,
      sceneWidth: 170,
      spans: [
        { length: 24, obstacle: 'road', width: 7, elevation: 0, angle: 90 },
        { length: 58, obstacle: 'water', width: 36, elevation: 0, angle: 90 },
        { length: 24, obstacle: 'road', width: 7, elevation: 0, angle: 90 },
      ],
    },
  },
  {
    id: 'deck-arch',
    label: 'Concrete deck arch',
    description: 'A 96 m concrete arch springing from the valley slopes, spandrel columns carrying a box girder deck, in a cut valley.',
    config: {
      ...defaults,
      structureSystem: 'arch',
      archType: 'deck',
      archMaterial: 'concrete',
      material: 'psbox',
      width: 12.4,
      depth: 1.4,
      variableDepth: false,
      continuous: true,
      elevation: 26,
      rise: 0.6,
      approach: 34,
      terrainShape: 'profile',
      leftRailing: '311A',
      rightRailing: '311A',
      pierType: 'wall',
      wallThickness: 1.2,
      environment: 'rural',
      seed: 83,
      sceneWidth: 200,
      spans: [
        { length: 22, obstacle: 'road', width: 6, elevation: 0, angle: 90 },
        { length: 96, obstacle: 'water', width: 40, elevation: 0, angle: 90 },
        { length: 22, obstacle: 'road', width: 6, elevation: 0, angle: 90 },
      ],
    },
  },
  {
    id: 'tied-arch',
    label: 'Steel tied arch',
    description: 'An 86 m bowstring arch in steel: inclined ribs, hangers every 4.5 m, wind bracing over the traffic.',
    config: {
      ...defaults,
      structureSystem: 'arch',
      archType: 'tied',
      archMaterial: 'steel',
      archRise: 0.2,
      material: 'steel',
      steelColor: 'gray16515',
      width: 14,
      girders: 5,
      overhang: 1.4,
      depth: 1.8,
      variableDepth: false,
      continuous: false,
      elevation: 9,
      rise: 0.35,
      approach: 30,
      leftRailing: '311A',
      rightRailing: '311A',
      sidewalkSide: 'none',
      lighting: 'poles',
      lightSides: 'both',
      environment: 'rural',
      seed: 95,
      sceneWidth: 170,
      spans: [{ length: 86, obstacle: 'water', width: 58, elevation: 0, angle: 90 }],
    },
  },
  {
    id: 'portal',
    label: 'Rigid frame · portique',
    description: 'A 22 m skewed concrete portal frame over a road: haunched solid slab built into its abutment walls.',
    config: {
      ...defaults,
      structureSystem: 'frame',
      material: 'slab',
      slabDepth: 0.85,
      variableDepth: true,
      pierDepth: 1.5,
      taper: 30,
      continuous: true,
      skew: 15,
      width: 13,
      elevation: 7.2,
      rise: 0.2,
      approach: 24,
      leftRailing: '201',
      rightRailing: '201',
      environment: 'urban',
      seed: 104,
      spans: [{ length: 22, obstacle: 'road', width: 12, elevation: 0, angle: 75 }],
    },
  },
];

export function makePreset(id) {
  const preset = presets.find(p => p.id === id);
  if (!preset) throw Error('Select a bridge preset.');
  const config = structuredClone(preset.config);
  // Box presets derive their top flanges and spacing from the bottom flange (1H:4V at typical depth).
  return validate(config.material === 'box' ? fitBoxLayoutFromBottom(config) : config);
}
